version: '3'

services:
    database_server:
        container_name: database_server
        hostname: database_server
        build: ./database_server
        ports:
            - "6379:6379"
        networks:
            - globNet
    stats_server:
        container_name: stats_server
        hostname: stats_server
        build: ./stats_server
        ports:
            - "6565:6565"
        networks:
            - globNet
    http_server:
        container_name: http_server
        hostname: http_server
        build: ./http_server
        ports:
            - "80:8080"
        networks:
            - globNet
        depends_on:
            - database_server
            - stats_server

networks:
    globNet:
        driver: bridge